version: '3.8'
services:
  dev-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: "checkout-db"
  test-db:
    image: mongo
    ports:
      -  27018:27017
    environment:
      MONGODB_DATABASE: "test-db"